language: php

# list any PHP version you want to test against
php:
  - 5.4

before_script:
  - cd ./test
  - php writeTestRunnerFile.php

script: phantomjs config/phantomjs_jasminexml_runner.js test-runner.html results